//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leet.Performance.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Leet.Performance.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to List cannot be null..
        /// </summary>
        public static string Exception_Argument_NullList {
            get {
                return ResourceManager.GetString("Exception_Argument_NullList", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to List cannot contain null element..
        /// </summary>
        public static string Exception_Argument_NullListItem {
            get {
                return ResourceManager.GetString("Exception_Argument_NullListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Progress percentage value cannot be Not-a-Number (System.Double.NaN)..
        /// </summary>
        public static string Exception_Argument_ProgressPercentageValueNaN {
            get {
                return ResourceManager.GetString("Exception_Argument_ProgressPercentageValueNaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Progress percentage value cannot be less than zero nor greater than one..
        /// </summary>
        public static string Exception_ArgumentOutOfRange_ProgressPercentageValue {
            get {
                return ResourceManager.GetString("Exception_ArgumentOutOfRange_ProgressPercentageValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Number of repetitions must be greater than zero..
        /// </summary>
        public static string Exception_ArgumentOutOfRange_RepetitionsNonPositive {
            get {
                return ResourceManager.GetString("Exception_ArgumentOutOfRange_RepetitionsNonPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Number of performance scenarios must be greater than zero..
        /// </summary>
        public static string Exception_ArgumentOutOfRange_ScenarioCountNonPositive {
            get {
                return ResourceManager.GetString("Exception_ArgumentOutOfRange_ScenarioCountNonPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Amount of elapsed ticks cannot be less than zero..
        /// </summary>
        public static string Exception_ArgumentOutOfRange_TicksElapsed {
            get {
                return ResourceManager.GetString("Exception_ArgumentOutOfRange_TicksElapsed", resourceCulture);
            }
        }
    }
}
